### ISSUE TITLE
Sentinel type difference with Zig 0.14.0 in mapGetN

### ISSUE THREAD

**Issue by adworacz** [dnjulek/vapoursynth-zig#9]
Ran into this while working on upgrading to Zig 0.14. Looks like they started requiring sentinel terminated strings for all C-interop, which I guess makes sense.

I suspect that it is a very simple fix - we just change the key type to `[* :0]const u8` instead and then the Zig compiler figures out the rest.

https://github.com/dnjulek/vapoursynth-zig/blob/7cb6779c4e40fb7415def9c60162e86ccd0eaa93/src/vshelper.zig#L112

Errors:

```sh
/home/adub/.cache/zig/p/vapoursynth-4.0.0-jLYMQw-HAgBK4pMJZBYzTNJuv5uuRlzKqpuY0sd2c_gi/src/vshelper.zig:115:59: error: expected type '[*:0]const u8', found '[*]co
nst u8'
        .int => math.lossyCast(T, vsapi.?.mapGetInt.?(in, key, @intCast(index), &err)),
                                                          ^~~
/home/adub/.cache/zig/p/vapoursynth-4.0.0-jLYMQw-HAgBK4pMJZBYzTNJuv5uuRlzKqpuY0sd2c_gi/src/vshelper.zig:115:59: note: destination pointer requires '0' sentinel
/home/adub/.cache/zig/p/vapoursynth-4.0.0-jLYMQw-HAgBK4pMJZBYzTNJuv5uuRlzKqpuY0sd2c_gi/src/vshelper.zig:115:59: error: expected type '[*:0]const u8', found '[*]co
nst u8'
        .int => math.lossyCast(T, vsapi.?.mapGetInt.?(in, key, @intCast(index), &err)),
                                                          ^~~
/home/adub/.cache/zig/p/vapoursynth-4.0.0-jLYMQw-HAgBK4pMJZBYzTNJuv5uuRlzKqpuY0sd2c_gi/src/vshelper.zig:115:59: note: destination pointer requires '0' sentinel
/home/adub/.cache/zig/p/vapoursynth-4.0.0-jLYMQw-HAgBK4pMJZBYzTNJuv5uuRlzKqpuY0sd2c_gi/src/vshelper.zig:115:59: error: expected type '[*:0]const u8', found '[*]co
nst u8'
        .int => math.lossyCast(T, vsapi.?.mapGetInt.?(in, key, @intCast(index), &err)),
                                                          ^~~
/home/adub/.cache/zig/p/vapoursynth-4.0.0-jLYMQw-HAgBK4pMJZBYzTNJuv5uuRlzKqpuY0sd2c_gi/src/vshelper.zig:115:59: note: destination pointer requires '0' sentinel
/home/adub/.cache/zig/p/vapoursynth-4.0.0-jLYMQw-HAgBK4pMJZBYzTNJuv5uuRlzKqpuY0sd2c_gi/src/vshelper.zig:116:63: error: expected type '[*:0]const u8', found '[*]co
nst u8'
        .float => math.lossyCast(T, vsapi.?.mapGetFloat.?(in, key, @intCast(index), &err)),
                                                              ^~~
/home/adub/.cache/zig/p/vapoursynth-4.0.0-jLYMQw-HAgBK4pMJZBYzTNJuv5uuRlzKqpuY0sd2c_gi/src/vshelper.zig:116:63: note: destination pointer requires '0' sentinel
/home/adub/.cache/zig/p/vapoursynth-4.0.0-jLYMQw-HAgBK4pMJZBYzTNJuv5uuRlzKqpuY0sd2c_gi/src/vshelper.zig:117:42: error: expected type '[*:0]const u8', found '[*]co
nst u8'
        .bool => vsapi.?.mapGetInt.?(in, key, @intCast(index), &err) != 0,
                                         ^~~
/home/adub/.cache/zig/p/vapoursynth-4.0.0-jLYMQw-HAgBK4pMJZBYzTNJuv5uuRlzKqpuY0sd2c_gi/src/vshelper.zig:117:42: note: destination pointer requires '0' sentinel
```

**Comment by dnjulek** [comment]
This is actually my fault, I introduced this in the API and I didn't test this func because I don't use it anymore, I only use the [new ZMap](https://github.com/dnjulek/vapoursynth-zig/blob/main/examples/example-zigapi/src/invert_example.zig#L79-L81), I'll fix it later.

**Comment by adworacz** [comment]
Yup totally fair. I figured that was the case. Eventually I’ll migrate to the new API as it is much cleaner (nice job on that btw), but doing so is a whole lot more code changes if I update all of my functions properly, so I’m doing the bare minimum of a migration for now.

**Comment by adworacz** [comment]
That worked like a charm, thank you!
